/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as authAccountsIndexImport } from './routes/(auth)/accounts/index'
import { Route as authAccountsCreateIndexImport } from './routes/(auth)/accounts/create/index'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authAccountsIndexRoute = authAccountsIndexImport.update({
  id: '/(auth)/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
} as any)

const authAccountsCreateIndexRoute = authAccountsCreateIndexImport.update({
  id: '/(auth)/accounts/create/',
  path: '/accounts/create/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/accounts/': {
      id: '/(auth)/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof authAccountsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/accounts/create/': {
      id: '/(auth)/accounts/create/'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof authAccountsCreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accounts': typeof authAccountsIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/accounts': typeof authAccountsIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/(auth)/accounts/': typeof authAccountsIndexRoute
  '/(auth)/accounts/create/': typeof authAccountsCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/accounts' | '/accounts/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/accounts' | '/accounts/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/accounts/'
    | '/(auth)/accounts/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  authAccountsIndexRoute: typeof authAccountsIndexRoute
  authAccountsCreateIndexRoute: typeof authAccountsCreateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  authAccountsIndexRoute: authAccountsIndexRoute,
  authAccountsCreateIndexRoute: authAccountsCreateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/(auth)/accounts/",
        "/(auth)/accounts/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/(auth)/accounts/": {
      "filePath": "(auth)/accounts/index.tsx"
    },
    "/(auth)/accounts/create/": {
      "filePath": "(auth)/accounts/create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
