/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as authSettingsIndexImport } from './routes/(auth)/settings/index'
import { Route as authDashboardIndexImport } from './routes/(auth)/dashboard/index'
import { Route as authBrokersIndexImport } from './routes/(auth)/brokers/index'
import { Route as authAccountsIndexImport } from './routes/(auth)/accounts/index'
import { Route as authAccountsSlugRouteImport } from './routes/(auth)/accounts/$slug/route'
import { Route as authBrokersCreateIndexImport } from './routes/(auth)/brokers/create/index'
import { Route as authAccountsCreateIndexImport } from './routes/(auth)/accounts/create/index'
import { Route as authAccountsSlugIndexImport } from './routes/(auth)/accounts/$slug/index'
import { Route as authAccountsSlugStatementsIndexImport } from './routes/(auth)/accounts/$slug/statements/index'
import { Route as authAccountsSlugCreditCardIndexImport } from './routes/(auth)/accounts/$slug/credit-card/index'
import { Route as authAccountsSlugCreditCardNewIndexImport } from './routes/(auth)/accounts/$slug/credit-card/new/index'
import { Route as authAccountsSlugCreditCardCreditCardIdIndexImport } from './routes/(auth)/accounts/$slug/credit-card/$creditCardId/index'

// Create/Update Routes

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authSettingsIndexRoute = authSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authRouteRoute,
} as any)

const authDashboardIndexRoute = authDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authRouteRoute,
} as any)

const authBrokersIndexRoute = authBrokersIndexImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => authRouteRoute,
} as any)

const authAccountsIndexRoute = authAccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => authRouteRoute,
} as any)

const authAccountsSlugRouteRoute = authAccountsSlugRouteImport.update({
  id: '/accounts/$slug',
  path: '/accounts/$slug',
  getParentRoute: () => authRouteRoute,
} as any)

const authBrokersCreateIndexRoute = authBrokersCreateIndexImport.update({
  id: '/brokers/create/',
  path: '/brokers/create/',
  getParentRoute: () => authRouteRoute,
} as any)

const authAccountsCreateIndexRoute = authAccountsCreateIndexImport.update({
  id: '/accounts/create/',
  path: '/accounts/create/',
  getParentRoute: () => authRouteRoute,
} as any)

const authAccountsSlugIndexRoute = authAccountsSlugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAccountsSlugRouteRoute,
} as any)

const authAccountsSlugStatementsIndexRoute =
  authAccountsSlugStatementsIndexImport.update({
    id: '/statements/',
    path: '/statements/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

const authAccountsSlugCreditCardIndexRoute =
  authAccountsSlugCreditCardIndexImport.update({
    id: '/credit-card/',
    path: '/credit-card/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

const authAccountsSlugCreditCardNewIndexRoute =
  authAccountsSlugCreditCardNewIndexImport.update({
    id: '/credit-card/new/',
    path: '/credit-card/new/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

const authAccountsSlugCreditCardCreditCardIdIndexRoute =
  authAccountsSlugCreditCardCreditCardIdIndexImport.update({
    id: '/credit-card/$creditCardId/',
    path: '/credit-card/$creditCardId/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/accounts/$slug': {
      id: '/(auth)/accounts/$slug'
      path: '/accounts/$slug'
      fullPath: '/accounts/$slug'
      preLoaderRoute: typeof authAccountsSlugRouteImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/accounts/': {
      id: '/(auth)/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof authAccountsIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/brokers/': {
      id: '/(auth)/brokers/'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof authBrokersIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/settings/': {
      id: '/(auth)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authSettingsIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/accounts/$slug/': {
      id: '/(auth)/accounts/$slug/'
      path: '/'
      fullPath: '/accounts/$slug/'
      preLoaderRoute: typeof authAccountsSlugIndexImport
      parentRoute: typeof authAccountsSlugRouteImport
    }
    '/(auth)/accounts/create/': {
      id: '/(auth)/accounts/create/'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof authAccountsCreateIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/brokers/create/': {
      id: '/(auth)/brokers/create/'
      path: '/brokers/create'
      fullPath: '/brokers/create'
      preLoaderRoute: typeof authBrokersCreateIndexImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/accounts/$slug/credit-card/': {
      id: '/(auth)/accounts/$slug/credit-card/'
      path: '/credit-card'
      fullPath: '/accounts/$slug/credit-card'
      preLoaderRoute: typeof authAccountsSlugCreditCardIndexImport
      parentRoute: typeof authAccountsSlugRouteImport
    }
    '/(auth)/accounts/$slug/statements/': {
      id: '/(auth)/accounts/$slug/statements/'
      path: '/statements'
      fullPath: '/accounts/$slug/statements'
      preLoaderRoute: typeof authAccountsSlugStatementsIndexImport
      parentRoute: typeof authAccountsSlugRouteImport
    }
    '/(auth)/accounts/$slug/credit-card/$creditCardId/': {
      id: '/(auth)/accounts/$slug/credit-card/$creditCardId/'
      path: '/credit-card/$creditCardId'
      fullPath: '/accounts/$slug/credit-card/$creditCardId'
      preLoaderRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexImport
      parentRoute: typeof authAccountsSlugRouteImport
    }
    '/(auth)/accounts/$slug/credit-card/new/': {
      id: '/(auth)/accounts/$slug/credit-card/new/'
      path: '/credit-card/new'
      fullPath: '/accounts/$slug/credit-card/new'
      preLoaderRoute: typeof authAccountsSlugCreditCardNewIndexImport
      parentRoute: typeof authAccountsSlugRouteImport
    }
  }
}

// Create and export the route tree

interface authAccountsSlugRouteRouteChildren {
  authAccountsSlugIndexRoute: typeof authAccountsSlugIndexRoute
  authAccountsSlugCreditCardIndexRoute: typeof authAccountsSlugCreditCardIndexRoute
  authAccountsSlugStatementsIndexRoute: typeof authAccountsSlugStatementsIndexRoute
  authAccountsSlugCreditCardCreditCardIdIndexRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
  authAccountsSlugCreditCardNewIndexRoute: typeof authAccountsSlugCreditCardNewIndexRoute
}

const authAccountsSlugRouteRouteChildren: authAccountsSlugRouteRouteChildren = {
  authAccountsSlugIndexRoute: authAccountsSlugIndexRoute,
  authAccountsSlugCreditCardIndexRoute: authAccountsSlugCreditCardIndexRoute,
  authAccountsSlugStatementsIndexRoute: authAccountsSlugStatementsIndexRoute,
  authAccountsSlugCreditCardCreditCardIdIndexRoute:
    authAccountsSlugCreditCardCreditCardIdIndexRoute,
  authAccountsSlugCreditCardNewIndexRoute:
    authAccountsSlugCreditCardNewIndexRoute,
}

const authAccountsSlugRouteRouteWithChildren =
  authAccountsSlugRouteRoute._addFileChildren(
    authAccountsSlugRouteRouteChildren,
  )

interface authRouteRouteChildren {
  authAccountsSlugRouteRoute: typeof authAccountsSlugRouteRouteWithChildren
  authAccountsIndexRoute: typeof authAccountsIndexRoute
  authBrokersIndexRoute: typeof authBrokersIndexRoute
  authDashboardIndexRoute: typeof authDashboardIndexRoute
  authSettingsIndexRoute: typeof authSettingsIndexRoute
  authAccountsCreateIndexRoute: typeof authAccountsCreateIndexRoute
  authBrokersCreateIndexRoute: typeof authBrokersCreateIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAccountsSlugRouteRoute: authAccountsSlugRouteRouteWithChildren,
  authAccountsIndexRoute: authAccountsIndexRoute,
  authBrokersIndexRoute: authBrokersIndexRoute,
  authDashboardIndexRoute: authDashboardIndexRoute,
  authSettingsIndexRoute: authSettingsIndexRoute,
  authAccountsCreateIndexRoute: authAccountsCreateIndexRoute,
  authBrokersCreateIndexRoute: authBrokersCreateIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
  '/accounts/$slug/credit-card/new': typeof authAccountsSlugCreditCardNewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/accounts/$slug': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
  '/accounts/$slug/credit-card/new': typeof authAccountsSlugCreditCardNewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/(auth)/accounts/': typeof authAccountsIndexRoute
  '/(auth)/brokers/': typeof authBrokersIndexRoute
  '/(auth)/dashboard/': typeof authDashboardIndexRoute
  '/(auth)/settings/': typeof authSettingsIndexRoute
  '/(auth)/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/(auth)/accounts/create/': typeof authAccountsCreateIndexRoute
  '/(auth)/brokers/create/': typeof authBrokersCreateIndexRoute
  '/(auth)/accounts/$slug/credit-card/': typeof authAccountsSlugCreditCardIndexRoute
  '/(auth)/accounts/$slug/statements/': typeof authAccountsSlugStatementsIndexRoute
  '/(auth)/accounts/$slug/credit-card/$creditCardId/': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
  '/(auth)/accounts/$slug/credit-card/new/': typeof authAccountsSlugCreditCardNewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$slug'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/settings'
    | '/accounts/$slug/'
    | '/accounts/create'
    | '/brokers/create'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/credit-card/$creditCardId'
    | '/accounts/$slug/credit-card/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/settings'
    | '/accounts/$slug'
    | '/accounts/create'
    | '/brokers/create'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/credit-card/$creditCardId'
    | '/accounts/$slug/credit-card/new'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/accounts/$slug'
    | '/(auth)/accounts/'
    | '/(auth)/brokers/'
    | '/(auth)/dashboard/'
    | '/(auth)/settings/'
    | '/(auth)/accounts/$slug/'
    | '/(auth)/accounts/create/'
    | '/(auth)/brokers/create/'
    | '/(auth)/accounts/$slug/credit-card/'
    | '/(auth)/accounts/$slug/statements/'
    | '/(auth)/accounts/$slug/credit-card/$creditCardId/'
    | '/(auth)/accounts/$slug/credit-card/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/accounts/$slug",
        "/(auth)/accounts/",
        "/(auth)/brokers/",
        "/(auth)/dashboard/",
        "/(auth)/settings/",
        "/(auth)/accounts/create/",
        "/(auth)/brokers/create/"
      ]
    },
    "/(auth)/accounts/$slug": {
      "filePath": "(auth)/accounts/$slug/route.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/accounts/$slug/",
        "/(auth)/accounts/$slug/credit-card/",
        "/(auth)/accounts/$slug/statements/",
        "/(auth)/accounts/$slug/credit-card/$creditCardId/",
        "/(auth)/accounts/$slug/credit-card/new/"
      ]
    },
    "/(auth)/accounts/": {
      "filePath": "(auth)/accounts/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/brokers/": {
      "filePath": "(auth)/brokers/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/dashboard/": {
      "filePath": "(auth)/dashboard/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/settings/": {
      "filePath": "(auth)/settings/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/accounts/$slug/": {
      "filePath": "(auth)/accounts/$slug/index.tsx",
      "parent": "/(auth)/accounts/$slug"
    },
    "/(auth)/accounts/create/": {
      "filePath": "(auth)/accounts/create/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/brokers/create/": {
      "filePath": "(auth)/brokers/create/index.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/accounts/$slug/credit-card/": {
      "filePath": "(auth)/accounts/$slug/credit-card/index.tsx",
      "parent": "/(auth)/accounts/$slug"
    },
    "/(auth)/accounts/$slug/statements/": {
      "filePath": "(auth)/accounts/$slug/statements/index.tsx",
      "parent": "/(auth)/accounts/$slug"
    },
    "/(auth)/accounts/$slug/credit-card/$creditCardId/": {
      "filePath": "(auth)/accounts/$slug/credit-card/$creditCardId/index.tsx",
      "parent": "/(auth)/accounts/$slug"
    },
    "/(auth)/accounts/$slug/credit-card/new/": {
      "filePath": "(auth)/accounts/$slug/credit-card/new/index.tsx",
      "parent": "/(auth)/accounts/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
