/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authTremorDemoRouteImport } from './routes/(auth)/tremor-demo'
import { Route as authReactAriaDemoRouteImport } from './routes/(auth)/react-aria-demo'
import { Route as authVendorsIndexRouteImport } from './routes/(auth)/vendors/index'
import { Route as authTransactionsIndexRouteImport } from './routes/(auth)/transactions/index'
import { Route as authSubscriptionsIndexRouteImport } from './routes/(auth)/subscriptions/index'
import { Route as authSettingsIndexRouteImport } from './routes/(auth)/settings/index'
import { Route as authInvestmentsIndexRouteImport } from './routes/(auth)/investments/index'
import { Route as authDashboardIndexRouteImport } from './routes/(auth)/dashboard/index'
import { Route as authBrokersIndexRouteImport } from './routes/(auth)/brokers/index'
import { Route as authAccountsIndexRouteImport } from './routes/(auth)/accounts/index'
import { Route as authVendorsCreateRouteImport } from './routes/(auth)/vendors/create'
import { Route as authSubscriptionsCreateRouteImport } from './routes/(auth)/subscriptions/create'
import { Route as authAccountsSlugRouteRouteImport } from './routes/(auth)/accounts/$slug/route'
import { Route as authVendorsVendorIdIndexRouteImport } from './routes/(auth)/vendors/$vendorId/index'
import { Route as authSubscriptionsSubscriptionIdIndexRouteImport } from './routes/(auth)/subscriptions/$subscriptionId/index'
import { Route as authBrokersCreateIndexRouteImport } from './routes/(auth)/brokers/create/index'
import { Route as authAccountsCreateIndexRouteImport } from './routes/(auth)/accounts/create/index'
import { Route as authAccountsSlugIndexRouteImport } from './routes/(auth)/accounts/$slug/index'
import { Route as authAccountsSlugStatementsRouteRouteImport } from './routes/(auth)/accounts/$slug/statements/route'
import { Route as authAccountsSlugStatementsIndexRouteImport } from './routes/(auth)/accounts/$slug/statements/index'
import { Route as authAccountsSlugIncomeIndexRouteImport } from './routes/(auth)/accounts/$slug/income/index'
import { Route as authAccountsSlugExpensesIndexRouteImport } from './routes/(auth)/accounts/$slug/expenses/index'
import { Route as authAccountsSlugCreditCardIndexRouteImport } from './routes/(auth)/accounts/$slug/credit-card/index'
import { Route as authAccountsSlugStatementsUploadRouteImport } from './routes/(auth)/accounts/$slug/statements/upload'
import { Route as authAccountsSlugStatementsHistoryRouteImport } from './routes/(auth)/accounts/$slug/statements/history'
import { Route as authAccountsSlugCreditCardCreditCardIdIndexRouteImport } from './routes/(auth)/accounts/$slug/credit-card/$creditCardId/index'
import { Route as authAccountsSlugCreditCardCreditCardIdTransactionsRouteImport } from './routes/(auth)/accounts/$slug/credit-card/$creditCardId/transactions'
import { Route as authAccountsSlugCreditCardCreditCardIdInvoicesRouteImport } from './routes/(auth)/accounts/$slug/credit-card/$creditCardId/invoices'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authTremorDemoRoute = authTremorDemoRouteImport.update({
  id: '/tremor-demo',
  path: '/tremor-demo',
  getParentRoute: () => authRouteRoute,
} as any)
const authReactAriaDemoRoute = authReactAriaDemoRouteImport.update({
  id: '/react-aria-demo',
  path: '/react-aria-demo',
  getParentRoute: () => authRouteRoute,
} as any)
const authVendorsIndexRoute = authVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => authRouteRoute,
} as any)
const authTransactionsIndexRoute = authTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSubscriptionsIndexRoute = authSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSettingsIndexRoute = authSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authRouteRoute,
} as any)
const authInvestmentsIndexRoute = authInvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardIndexRoute = authDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authRouteRoute,
} as any)
const authBrokersIndexRoute = authBrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsIndexRoute = authAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => authRouteRoute,
} as any)
const authVendorsCreateRoute = authVendorsCreateRouteImport.update({
  id: '/vendors/create',
  path: '/vendors/create',
  getParentRoute: () => authRouteRoute,
} as any)
const authSubscriptionsCreateRoute = authSubscriptionsCreateRouteImport.update({
  id: '/subscriptions/create',
  path: '/subscriptions/create',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsSlugRouteRoute = authAccountsSlugRouteRouteImport.update({
  id: '/accounts/$slug',
  path: '/accounts/$slug',
  getParentRoute: () => authRouteRoute,
} as any)
const authVendorsVendorIdIndexRoute =
  authVendorsVendorIdIndexRouteImport.update({
    id: '/vendors/$vendorId/',
    path: '/vendors/$vendorId/',
    getParentRoute: () => authRouteRoute,
  } as any)
const authSubscriptionsSubscriptionIdIndexRoute =
  authSubscriptionsSubscriptionIdIndexRouteImport.update({
    id: '/subscriptions/$subscriptionId/',
    path: '/subscriptions/$subscriptionId/',
    getParentRoute: () => authRouteRoute,
  } as any)
const authBrokersCreateIndexRoute = authBrokersCreateIndexRouteImport.update({
  id: '/brokers/create/',
  path: '/brokers/create/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsCreateIndexRoute = authAccountsCreateIndexRouteImport.update({
  id: '/accounts/create/',
  path: '/accounts/create/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsSlugIndexRoute = authAccountsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAccountsSlugRouteRoute,
} as any)
const authAccountsSlugStatementsRouteRoute =
  authAccountsSlugStatementsRouteRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugStatementsIndexRoute =
  authAccountsSlugStatementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authAccountsSlugStatementsRouteRoute,
  } as any)
const authAccountsSlugIncomeIndexRoute =
  authAccountsSlugIncomeIndexRouteImport.update({
    id: '/income/',
    path: '/income/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugExpensesIndexRoute =
  authAccountsSlugExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugCreditCardIndexRoute =
  authAccountsSlugCreditCardIndexRouteImport.update({
    id: '/credit-card/',
    path: '/credit-card/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugStatementsUploadRoute =
  authAccountsSlugStatementsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => authAccountsSlugStatementsRouteRoute,
  } as any)
const authAccountsSlugStatementsHistoryRoute =
  authAccountsSlugStatementsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => authAccountsSlugStatementsRouteRoute,
  } as any)
const authAccountsSlugCreditCardCreditCardIdIndexRoute =
  authAccountsSlugCreditCardCreditCardIdIndexRouteImport.update({
    id: '/credit-card/$creditCardId/',
    path: '/credit-card/$creditCardId/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugCreditCardCreditCardIdTransactionsRoute =
  authAccountsSlugCreditCardCreditCardIdTransactionsRouteImport.update({
    id: '/credit-card/$creditCardId/transactions',
    path: '/credit-card/$creditCardId/transactions',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugCreditCardCreditCardIdInvoicesRoute =
  authAccountsSlugCreditCardCreditCardIdInvoicesRouteImport.update({
    id: '/credit-card/$creditCardId/invoices',
    path: '/credit-card/$creditCardId/invoices',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/react-aria-demo': typeof authReactAriaDemoRoute
  '/tremor-demo': typeof authTremorDemoRoute
  '/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/subscriptions/create': typeof authSubscriptionsCreateRoute
  '/vendors/create': typeof authVendorsCreateRoute
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/investments': typeof authInvestmentsIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/subscriptions': typeof authSubscriptionsIndexRoute
  '/transactions': typeof authTransactionsIndexRoute
  '/vendors': typeof authVendorsIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsRouteRouteWithChildren
  '/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/subscriptions/$subscriptionId': typeof authSubscriptionsSubscriptionIdIndexRoute
  '/vendors/$vendorId': typeof authVendorsVendorIdIndexRoute
  '/accounts/$slug/statements/history': typeof authAccountsSlugStatementsHistoryRoute
  '/accounts/$slug/statements/upload': typeof authAccountsSlugStatementsUploadRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/expenses': typeof authAccountsSlugExpensesIndexRoute
  '/accounts/$slug/income': typeof authAccountsSlugIncomeIndexRoute
  '/accounts/$slug/statements/': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId/invoices': typeof authAccountsSlugCreditCardCreditCardIdInvoicesRoute
  '/accounts/$slug/credit-card/$creditCardId/transactions': typeof authAccountsSlugCreditCardCreditCardIdTransactionsRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/react-aria-demo': typeof authReactAriaDemoRoute
  '/tremor-demo': typeof authTremorDemoRoute
  '/subscriptions/create': typeof authSubscriptionsCreateRoute
  '/vendors/create': typeof authVendorsCreateRoute
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/investments': typeof authInvestmentsIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/subscriptions': typeof authSubscriptionsIndexRoute
  '/transactions': typeof authTransactionsIndexRoute
  '/vendors': typeof authVendorsIndexRoute
  '/accounts/$slug': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/subscriptions/$subscriptionId': typeof authSubscriptionsSubscriptionIdIndexRoute
  '/vendors/$vendorId': typeof authVendorsVendorIdIndexRoute
  '/accounts/$slug/statements/history': typeof authAccountsSlugStatementsHistoryRoute
  '/accounts/$slug/statements/upload': typeof authAccountsSlugStatementsUploadRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/expenses': typeof authAccountsSlugExpensesIndexRoute
  '/accounts/$slug/income': typeof authAccountsSlugIncomeIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId/invoices': typeof authAccountsSlugCreditCardCreditCardIdInvoicesRoute
  '/accounts/$slug/credit-card/$creditCardId/transactions': typeof authAccountsSlugCreditCardCreditCardIdTransactionsRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(auth)/react-aria-demo': typeof authReactAriaDemoRoute
  '/(auth)/tremor-demo': typeof authTremorDemoRoute
  '/(auth)/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/(auth)/subscriptions/create': typeof authSubscriptionsCreateRoute
  '/(auth)/vendors/create': typeof authVendorsCreateRoute
  '/(auth)/accounts/': typeof authAccountsIndexRoute
  '/(auth)/brokers/': typeof authBrokersIndexRoute
  '/(auth)/dashboard/': typeof authDashboardIndexRoute
  '/(auth)/investments/': typeof authInvestmentsIndexRoute
  '/(auth)/settings/': typeof authSettingsIndexRoute
  '/(auth)/subscriptions/': typeof authSubscriptionsIndexRoute
  '/(auth)/transactions/': typeof authTransactionsIndexRoute
  '/(auth)/vendors/': typeof authVendorsIndexRoute
  '/(auth)/accounts/$slug/statements': typeof authAccountsSlugStatementsRouteRouteWithChildren
  '/(auth)/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/(auth)/accounts/create/': typeof authAccountsCreateIndexRoute
  '/(auth)/brokers/create/': typeof authBrokersCreateIndexRoute
  '/(auth)/subscriptions/$subscriptionId/': typeof authSubscriptionsSubscriptionIdIndexRoute
  '/(auth)/vendors/$vendorId/': typeof authVendorsVendorIdIndexRoute
  '/(auth)/accounts/$slug/statements/history': typeof authAccountsSlugStatementsHistoryRoute
  '/(auth)/accounts/$slug/statements/upload': typeof authAccountsSlugStatementsUploadRoute
  '/(auth)/accounts/$slug/credit-card/': typeof authAccountsSlugCreditCardIndexRoute
  '/(auth)/accounts/$slug/expenses/': typeof authAccountsSlugExpensesIndexRoute
  '/(auth)/accounts/$slug/income/': typeof authAccountsSlugIncomeIndexRoute
  '/(auth)/accounts/$slug/statements/': typeof authAccountsSlugStatementsIndexRoute
  '/(auth)/accounts/$slug/credit-card/$creditCardId/invoices': typeof authAccountsSlugCreditCardCreditCardIdInvoicesRoute
  '/(auth)/accounts/$slug/credit-card/$creditCardId/transactions': typeof authAccountsSlugCreditCardCreditCardIdTransactionsRoute
  '/(auth)/accounts/$slug/credit-card/$creditCardId/': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/react-aria-demo'
    | '/tremor-demo'
    | '/accounts/$slug'
    | '/subscriptions/create'
    | '/vendors/create'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/investments'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/vendors'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/'
    | '/accounts/create'
    | '/brokers/create'
    | '/subscriptions/$subscriptionId'
    | '/vendors/$vendorId'
    | '/accounts/$slug/statements/history'
    | '/accounts/$slug/statements/upload'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/expenses'
    | '/accounts/$slug/income'
    | '/accounts/$slug/statements/'
    | '/accounts/$slug/credit-card/$creditCardId/invoices'
    | '/accounts/$slug/credit-card/$creditCardId/transactions'
    | '/accounts/$slug/credit-card/$creditCardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/react-aria-demo'
    | '/tremor-demo'
    | '/subscriptions/create'
    | '/vendors/create'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/investments'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/vendors'
    | '/accounts/$slug'
    | '/accounts/create'
    | '/brokers/create'
    | '/subscriptions/$subscriptionId'
    | '/vendors/$vendorId'
    | '/accounts/$slug/statements/history'
    | '/accounts/$slug/statements/upload'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/expenses'
    | '/accounts/$slug/income'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/credit-card/$creditCardId/invoices'
    | '/accounts/$slug/credit-card/$creditCardId/transactions'
    | '/accounts/$slug/credit-card/$creditCardId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/login'
    | '/signup'
    | '/(auth)/react-aria-demo'
    | '/(auth)/tremor-demo'
    | '/(auth)/accounts/$slug'
    | '/(auth)/subscriptions/create'
    | '/(auth)/vendors/create'
    | '/(auth)/accounts/'
    | '/(auth)/brokers/'
    | '/(auth)/dashboard/'
    | '/(auth)/investments/'
    | '/(auth)/settings/'
    | '/(auth)/subscriptions/'
    | '/(auth)/transactions/'
    | '/(auth)/vendors/'
    | '/(auth)/accounts/$slug/statements'
    | '/(auth)/accounts/$slug/'
    | '/(auth)/accounts/create/'
    | '/(auth)/brokers/create/'
    | '/(auth)/subscriptions/$subscriptionId/'
    | '/(auth)/vendors/$vendorId/'
    | '/(auth)/accounts/$slug/statements/history'
    | '/(auth)/accounts/$slug/statements/upload'
    | '/(auth)/accounts/$slug/credit-card/'
    | '/(auth)/accounts/$slug/expenses/'
    | '/(auth)/accounts/$slug/income/'
    | '/(auth)/accounts/$slug/statements/'
    | '/(auth)/accounts/$slug/credit-card/$creditCardId/invoices'
    | '/(auth)/accounts/$slug/credit-card/$creditCardId/transactions'
    | '/(auth)/accounts/$slug/credit-card/$creditCardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/tremor-demo': {
      id: '/(auth)/tremor-demo'
      path: '/tremor-demo'
      fullPath: '/tremor-demo'
      preLoaderRoute: typeof authTremorDemoRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/react-aria-demo': {
      id: '/(auth)/react-aria-demo'
      path: '/react-aria-demo'
      fullPath: '/react-aria-demo'
      preLoaderRoute: typeof authReactAriaDemoRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/vendors/': {
      id: '/(auth)/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof authVendorsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/transactions/': {
      id: '/(auth)/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof authTransactionsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/subscriptions/': {
      id: '/(auth)/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof authSubscriptionsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/settings/': {
      id: '/(auth)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authSettingsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/investments/': {
      id: '/(auth)/investments/'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof authInvestmentsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/brokers/': {
      id: '/(auth)/brokers/'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof authBrokersIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/': {
      id: '/(auth)/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof authAccountsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/vendors/create': {
      id: '/(auth)/vendors/create'
      path: '/vendors/create'
      fullPath: '/vendors/create'
      preLoaderRoute: typeof authVendorsCreateRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/subscriptions/create': {
      id: '/(auth)/subscriptions/create'
      path: '/subscriptions/create'
      fullPath: '/subscriptions/create'
      preLoaderRoute: typeof authSubscriptionsCreateRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/$slug': {
      id: '/(auth)/accounts/$slug'
      path: '/accounts/$slug'
      fullPath: '/accounts/$slug'
      preLoaderRoute: typeof authAccountsSlugRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/vendors/$vendorId/': {
      id: '/(auth)/vendors/$vendorId/'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof authVendorsVendorIdIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/subscriptions/$subscriptionId/': {
      id: '/(auth)/subscriptions/$subscriptionId/'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/subscriptions/$subscriptionId'
      preLoaderRoute: typeof authSubscriptionsSubscriptionIdIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/brokers/create/': {
      id: '/(auth)/brokers/create/'
      path: '/brokers/create'
      fullPath: '/brokers/create'
      preLoaderRoute: typeof authBrokersCreateIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/create/': {
      id: '/(auth)/accounts/create/'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof authAccountsCreateIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/$slug/': {
      id: '/(auth)/accounts/$slug/'
      path: '/'
      fullPath: '/accounts/$slug/'
      preLoaderRoute: typeof authAccountsSlugIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/statements': {
      id: '/(auth)/accounts/$slug/statements'
      path: '/statements'
      fullPath: '/accounts/$slug/statements'
      preLoaderRoute: typeof authAccountsSlugStatementsRouteRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/statements/': {
      id: '/(auth)/accounts/$slug/statements/'
      path: '/'
      fullPath: '/accounts/$slug/statements/'
      preLoaderRoute: typeof authAccountsSlugStatementsIndexRouteImport
      parentRoute: typeof authAccountsSlugStatementsRouteRoute
    }
    '/(auth)/accounts/$slug/income/': {
      id: '/(auth)/accounts/$slug/income/'
      path: '/income'
      fullPath: '/accounts/$slug/income'
      preLoaderRoute: typeof authAccountsSlugIncomeIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/expenses/': {
      id: '/(auth)/accounts/$slug/expenses/'
      path: '/expenses'
      fullPath: '/accounts/$slug/expenses'
      preLoaderRoute: typeof authAccountsSlugExpensesIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/': {
      id: '/(auth)/accounts/$slug/credit-card/'
      path: '/credit-card'
      fullPath: '/accounts/$slug/credit-card'
      preLoaderRoute: typeof authAccountsSlugCreditCardIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/statements/upload': {
      id: '/(auth)/accounts/$slug/statements/upload'
      path: '/upload'
      fullPath: '/accounts/$slug/statements/upload'
      preLoaderRoute: typeof authAccountsSlugStatementsUploadRouteImport
      parentRoute: typeof authAccountsSlugStatementsRouteRoute
    }
    '/(auth)/accounts/$slug/statements/history': {
      id: '/(auth)/accounts/$slug/statements/history'
      path: '/history'
      fullPath: '/accounts/$slug/statements/history'
      preLoaderRoute: typeof authAccountsSlugStatementsHistoryRouteImport
      parentRoute: typeof authAccountsSlugStatementsRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/$creditCardId/': {
      id: '/(auth)/accounts/$slug/credit-card/$creditCardId/'
      path: '/credit-card/$creditCardId'
      fullPath: '/accounts/$slug/credit-card/$creditCardId'
      preLoaderRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/$creditCardId/transactions': {
      id: '/(auth)/accounts/$slug/credit-card/$creditCardId/transactions'
      path: '/credit-card/$creditCardId/transactions'
      fullPath: '/accounts/$slug/credit-card/$creditCardId/transactions'
      preLoaderRoute: typeof authAccountsSlugCreditCardCreditCardIdTransactionsRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/$creditCardId/invoices': {
      id: '/(auth)/accounts/$slug/credit-card/$creditCardId/invoices'
      path: '/credit-card/$creditCardId/invoices'
      fullPath: '/accounts/$slug/credit-card/$creditCardId/invoices'
      preLoaderRoute: typeof authAccountsSlugCreditCardCreditCardIdInvoicesRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
  }
}

interface authAccountsSlugStatementsRouteRouteChildren {
  authAccountsSlugStatementsHistoryRoute: typeof authAccountsSlugStatementsHistoryRoute
  authAccountsSlugStatementsUploadRoute: typeof authAccountsSlugStatementsUploadRoute
  authAccountsSlugStatementsIndexRoute: typeof authAccountsSlugStatementsIndexRoute
}

const authAccountsSlugStatementsRouteRouteChildren: authAccountsSlugStatementsRouteRouteChildren =
  {
    authAccountsSlugStatementsHistoryRoute:
      authAccountsSlugStatementsHistoryRoute,
    authAccountsSlugStatementsUploadRoute:
      authAccountsSlugStatementsUploadRoute,
    authAccountsSlugStatementsIndexRoute: authAccountsSlugStatementsIndexRoute,
  }

const authAccountsSlugStatementsRouteRouteWithChildren =
  authAccountsSlugStatementsRouteRoute._addFileChildren(
    authAccountsSlugStatementsRouteRouteChildren,
  )

interface authAccountsSlugRouteRouteChildren {
  authAccountsSlugStatementsRouteRoute: typeof authAccountsSlugStatementsRouteRouteWithChildren
  authAccountsSlugIndexRoute: typeof authAccountsSlugIndexRoute
  authAccountsSlugCreditCardIndexRoute: typeof authAccountsSlugCreditCardIndexRoute
  authAccountsSlugExpensesIndexRoute: typeof authAccountsSlugExpensesIndexRoute
  authAccountsSlugIncomeIndexRoute: typeof authAccountsSlugIncomeIndexRoute
  authAccountsSlugCreditCardCreditCardIdInvoicesRoute: typeof authAccountsSlugCreditCardCreditCardIdInvoicesRoute
  authAccountsSlugCreditCardCreditCardIdTransactionsRoute: typeof authAccountsSlugCreditCardCreditCardIdTransactionsRoute
  authAccountsSlugCreditCardCreditCardIdIndexRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}

const authAccountsSlugRouteRouteChildren: authAccountsSlugRouteRouteChildren = {
  authAccountsSlugStatementsRouteRoute:
    authAccountsSlugStatementsRouteRouteWithChildren,
  authAccountsSlugIndexRoute: authAccountsSlugIndexRoute,
  authAccountsSlugCreditCardIndexRoute: authAccountsSlugCreditCardIndexRoute,
  authAccountsSlugExpensesIndexRoute: authAccountsSlugExpensesIndexRoute,
  authAccountsSlugIncomeIndexRoute: authAccountsSlugIncomeIndexRoute,
  authAccountsSlugCreditCardCreditCardIdInvoicesRoute:
    authAccountsSlugCreditCardCreditCardIdInvoicesRoute,
  authAccountsSlugCreditCardCreditCardIdTransactionsRoute:
    authAccountsSlugCreditCardCreditCardIdTransactionsRoute,
  authAccountsSlugCreditCardCreditCardIdIndexRoute:
    authAccountsSlugCreditCardCreditCardIdIndexRoute,
}

const authAccountsSlugRouteRouteWithChildren =
  authAccountsSlugRouteRoute._addFileChildren(
    authAccountsSlugRouteRouteChildren,
  )

interface authRouteRouteChildren {
  authReactAriaDemoRoute: typeof authReactAriaDemoRoute
  authTremorDemoRoute: typeof authTremorDemoRoute
  authAccountsSlugRouteRoute: typeof authAccountsSlugRouteRouteWithChildren
  authSubscriptionsCreateRoute: typeof authSubscriptionsCreateRoute
  authVendorsCreateRoute: typeof authVendorsCreateRoute
  authAccountsIndexRoute: typeof authAccountsIndexRoute
  authBrokersIndexRoute: typeof authBrokersIndexRoute
  authDashboardIndexRoute: typeof authDashboardIndexRoute
  authInvestmentsIndexRoute: typeof authInvestmentsIndexRoute
  authSettingsIndexRoute: typeof authSettingsIndexRoute
  authSubscriptionsIndexRoute: typeof authSubscriptionsIndexRoute
  authTransactionsIndexRoute: typeof authTransactionsIndexRoute
  authVendorsIndexRoute: typeof authVendorsIndexRoute
  authAccountsCreateIndexRoute: typeof authAccountsCreateIndexRoute
  authBrokersCreateIndexRoute: typeof authBrokersCreateIndexRoute
  authSubscriptionsSubscriptionIdIndexRoute: typeof authSubscriptionsSubscriptionIdIndexRoute
  authVendorsVendorIdIndexRoute: typeof authVendorsVendorIdIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authReactAriaDemoRoute: authReactAriaDemoRoute,
  authTremorDemoRoute: authTremorDemoRoute,
  authAccountsSlugRouteRoute: authAccountsSlugRouteRouteWithChildren,
  authSubscriptionsCreateRoute: authSubscriptionsCreateRoute,
  authVendorsCreateRoute: authVendorsCreateRoute,
  authAccountsIndexRoute: authAccountsIndexRoute,
  authBrokersIndexRoute: authBrokersIndexRoute,
  authDashboardIndexRoute: authDashboardIndexRoute,
  authInvestmentsIndexRoute: authInvestmentsIndexRoute,
  authSettingsIndexRoute: authSettingsIndexRoute,
  authSubscriptionsIndexRoute: authSubscriptionsIndexRoute,
  authTransactionsIndexRoute: authTransactionsIndexRoute,
  authVendorsIndexRoute: authVendorsIndexRoute,
  authAccountsCreateIndexRoute: authAccountsCreateIndexRoute,
  authBrokersCreateIndexRoute: authBrokersCreateIndexRoute,
  authSubscriptionsSubscriptionIdIndexRoute:
    authSubscriptionsSubscriptionIdIndexRoute,
  authVendorsVendorIdIndexRoute: authVendorsVendorIdIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
