/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authTransactionsIndexRouteImport } from './routes/(auth)/transactions/index'
import { Route as authSettingsIndexRouteImport } from './routes/(auth)/settings/index'
import { Route as authDashboardIndexRouteImport } from './routes/(auth)/dashboard/index'
import { Route as authBrokersIndexRouteImport } from './routes/(auth)/brokers/index'
import { Route as authAccountsIndexRouteImport } from './routes/(auth)/accounts/index'
import { Route as authAccountsSlugRouteRouteImport } from './routes/(auth)/accounts/$slug/route'
import { Route as authBrokersCreateIndexRouteImport } from './routes/(auth)/brokers/create/index'
import { Route as authAccountsCreateIndexRouteImport } from './routes/(auth)/accounts/create/index'
import { Route as authAccountsSlugIndexRouteImport } from './routes/(auth)/accounts/$slug/index'
import { Route as authAccountsSlugStatementsIndexRouteImport } from './routes/(auth)/accounts/$slug/statements/index'
import { Route as authAccountsSlugCreditCardIndexRouteImport } from './routes/(auth)/accounts/$slug/credit-card/index'
import { Route as authAccountsSlugCreditCardCreditCardIdIndexRouteImport } from './routes/(auth)/accounts/$slug/credit-card/$creditCardId/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authTransactionsIndexRoute = authTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSettingsIndexRoute = authSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardIndexRoute = authDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authRouteRoute,
} as any)
const authBrokersIndexRoute = authBrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsIndexRoute = authAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsSlugRouteRoute = authAccountsSlugRouteRouteImport.update({
  id: '/accounts/$slug',
  path: '/accounts/$slug',
  getParentRoute: () => authRouteRoute,
} as any)
const authBrokersCreateIndexRoute = authBrokersCreateIndexRouteImport.update({
  id: '/brokers/create/',
  path: '/brokers/create/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsCreateIndexRoute = authAccountsCreateIndexRouteImport.update({
  id: '/accounts/create/',
  path: '/accounts/create/',
  getParentRoute: () => authRouteRoute,
} as any)
const authAccountsSlugIndexRoute = authAccountsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAccountsSlugRouteRoute,
} as any)
const authAccountsSlugStatementsIndexRoute =
  authAccountsSlugStatementsIndexRouteImport.update({
    id: '/statements/',
    path: '/statements/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugCreditCardIndexRoute =
  authAccountsSlugCreditCardIndexRouteImport.update({
    id: '/credit-card/',
    path: '/credit-card/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)
const authAccountsSlugCreditCardCreditCardIdIndexRoute =
  authAccountsSlugCreditCardCreditCardIdIndexRouteImport.update({
    id: '/credit-card/$creditCardId/',
    path: '/credit-card/$creditCardId/',
    getParentRoute: () => authAccountsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/transactions': typeof authTransactionsIndexRoute
  '/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/accounts': typeof authAccountsIndexRoute
  '/brokers': typeof authBrokersIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/transactions': typeof authTransactionsIndexRoute
  '/accounts/$slug': typeof authAccountsSlugIndexRoute
  '/accounts/create': typeof authAccountsCreateIndexRoute
  '/brokers/create': typeof authBrokersCreateIndexRoute
  '/accounts/$slug/credit-card': typeof authAccountsSlugCreditCardIndexRoute
  '/accounts/$slug/statements': typeof authAccountsSlugStatementsIndexRoute
  '/accounts/$slug/credit-card/$creditCardId': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/accounts/$slug': typeof authAccountsSlugRouteRouteWithChildren
  '/(auth)/accounts/': typeof authAccountsIndexRoute
  '/(auth)/brokers/': typeof authBrokersIndexRoute
  '/(auth)/dashboard/': typeof authDashboardIndexRoute
  '/(auth)/settings/': typeof authSettingsIndexRoute
  '/(auth)/transactions/': typeof authTransactionsIndexRoute
  '/(auth)/accounts/$slug/': typeof authAccountsSlugIndexRoute
  '/(auth)/accounts/create/': typeof authAccountsCreateIndexRoute
  '/(auth)/brokers/create/': typeof authBrokersCreateIndexRoute
  '/(auth)/accounts/$slug/credit-card/': typeof authAccountsSlugCreditCardIndexRoute
  '/(auth)/accounts/$slug/statements/': typeof authAccountsSlugStatementsIndexRoute
  '/(auth)/accounts/$slug/credit-card/$creditCardId/': typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$slug'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/settings'
    | '/transactions'
    | '/accounts/$slug/'
    | '/accounts/create'
    | '/brokers/create'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/credit-card/$creditCardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/brokers'
    | '/dashboard'
    | '/settings'
    | '/transactions'
    | '/accounts/$slug'
    | '/accounts/create'
    | '/brokers/create'
    | '/accounts/$slug/credit-card'
    | '/accounts/$slug/statements'
    | '/accounts/$slug/credit-card/$creditCardId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/accounts/$slug'
    | '/(auth)/accounts/'
    | '/(auth)/brokers/'
    | '/(auth)/dashboard/'
    | '/(auth)/settings/'
    | '/(auth)/transactions/'
    | '/(auth)/accounts/$slug/'
    | '/(auth)/accounts/create/'
    | '/(auth)/brokers/create/'
    | '/(auth)/accounts/$slug/credit-card/'
    | '/(auth)/accounts/$slug/statements/'
    | '/(auth)/accounts/$slug/credit-card/$creditCardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/transactions/': {
      id: '/(auth)/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof authTransactionsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/settings/': {
      id: '/(auth)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authSettingsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/brokers/': {
      id: '/(auth)/brokers/'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof authBrokersIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/': {
      id: '/(auth)/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof authAccountsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/$slug': {
      id: '/(auth)/accounts/$slug'
      path: '/accounts/$slug'
      fullPath: '/accounts/$slug'
      preLoaderRoute: typeof authAccountsSlugRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/brokers/create/': {
      id: '/(auth)/brokers/create/'
      path: '/brokers/create'
      fullPath: '/brokers/create'
      preLoaderRoute: typeof authBrokersCreateIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/create/': {
      id: '/(auth)/accounts/create/'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof authAccountsCreateIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accounts/$slug/': {
      id: '/(auth)/accounts/$slug/'
      path: '/'
      fullPath: '/accounts/$slug/'
      preLoaderRoute: typeof authAccountsSlugIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/statements/': {
      id: '/(auth)/accounts/$slug/statements/'
      path: '/statements'
      fullPath: '/accounts/$slug/statements'
      preLoaderRoute: typeof authAccountsSlugStatementsIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/': {
      id: '/(auth)/accounts/$slug/credit-card/'
      path: '/credit-card'
      fullPath: '/accounts/$slug/credit-card'
      preLoaderRoute: typeof authAccountsSlugCreditCardIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
    '/(auth)/accounts/$slug/credit-card/$creditCardId/': {
      id: '/(auth)/accounts/$slug/credit-card/$creditCardId/'
      path: '/credit-card/$creditCardId'
      fullPath: '/accounts/$slug/credit-card/$creditCardId'
      preLoaderRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexRouteImport
      parentRoute: typeof authAccountsSlugRouteRoute
    }
  }
}

interface authAccountsSlugRouteRouteChildren {
  authAccountsSlugIndexRoute: typeof authAccountsSlugIndexRoute
  authAccountsSlugCreditCardIndexRoute: typeof authAccountsSlugCreditCardIndexRoute
  authAccountsSlugStatementsIndexRoute: typeof authAccountsSlugStatementsIndexRoute
  authAccountsSlugCreditCardCreditCardIdIndexRoute: typeof authAccountsSlugCreditCardCreditCardIdIndexRoute
}

const authAccountsSlugRouteRouteChildren: authAccountsSlugRouteRouteChildren = {
  authAccountsSlugIndexRoute: authAccountsSlugIndexRoute,
  authAccountsSlugCreditCardIndexRoute: authAccountsSlugCreditCardIndexRoute,
  authAccountsSlugStatementsIndexRoute: authAccountsSlugStatementsIndexRoute,
  authAccountsSlugCreditCardCreditCardIdIndexRoute:
    authAccountsSlugCreditCardCreditCardIdIndexRoute,
}

const authAccountsSlugRouteRouteWithChildren =
  authAccountsSlugRouteRoute._addFileChildren(
    authAccountsSlugRouteRouteChildren,
  )

interface authRouteRouteChildren {
  authAccountsSlugRouteRoute: typeof authAccountsSlugRouteRouteWithChildren
  authAccountsIndexRoute: typeof authAccountsIndexRoute
  authBrokersIndexRoute: typeof authBrokersIndexRoute
  authDashboardIndexRoute: typeof authDashboardIndexRoute
  authSettingsIndexRoute: typeof authSettingsIndexRoute
  authTransactionsIndexRoute: typeof authTransactionsIndexRoute
  authAccountsCreateIndexRoute: typeof authAccountsCreateIndexRoute
  authBrokersCreateIndexRoute: typeof authBrokersCreateIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAccountsSlugRouteRoute: authAccountsSlugRouteRouteWithChildren,
  authAccountsIndexRoute: authAccountsIndexRoute,
  authBrokersIndexRoute: authBrokersIndexRoute,
  authDashboardIndexRoute: authDashboardIndexRoute,
  authSettingsIndexRoute: authSettingsIndexRoute,
  authTransactionsIndexRoute: authTransactionsIndexRoute,
  authAccountsCreateIndexRoute: authAccountsCreateIndexRoute,
  authBrokersCreateIndexRoute: authBrokersCreateIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
